/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.scedule_gui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.*;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class ADD_set extends javax.swing.JFrame {

    /**
     * Creates new form ADD_set
     */
    JScrollPane sp;
    JLabel empty_lb;
    JPanel panel;
    String current_user=new String();
    String cureent_password=new String();
    Generics g_code=new Generics();
    JTable table;
    JTable d_Table;
    ImageIcon date_icon=new ImageIcon("Images\\lav_date.png");
    ImageIcon time_icon=new ImageIcon("Images\\lav_time.png");
    ImageIcon loc_icon=new ImageIcon("Images\\lav_loc.png");
    ImageIcon rem_icon=new ImageIcon("Images\\lav_bell.png");
    Color font_color;
    public ADD_set() {
        initComponents();
     Toolkit toolkit=getToolkit();
    Dimension size=toolkit.getScreenSize();
    this.setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
    this.Exit_btn.setIcon(new ImageIcon("Images\\icons8_Close_20px.png"));
    date_lb.setIcon(date_icon);
    Time_label.setIcon(time_icon);
    loc_lb.setIcon(loc_icon);
    rem_lb.setIcon(rem_icon);
    

        String[] days=new String[30];
        String[] months=new String[12];
        String[] years=new String[10];
        String[] hours=new String[24];
        String[] mins=new String[6];
        
        for(int i=1;i<31;i++)
        {
            days[i-1]=new String(String.valueOf(i));
        }
         for(int i=1;i<13;i++)
        {
            months[i-1]=new String(String.valueOf(i));
        }
         for(int i=0;i<9;i++)
        {
            years[i]=new String(String.valueOf(i+2022));
        }
         for(int i=1;i<25;i++)
        {
            hours[i-1]=new String(String.valueOf(i));
        }
         for(int i=0;i<6;i++)
        {
            mins[i]=new String(String.valueOf(i*10));
        }


        DefaultComboBoxModel dm=new DefaultComboBoxModel(days);
        Days_start_cm.setModel(dm);
        DefaultComboBoxModel mm=new DefaultComboBoxModel(months);
        month_start_cm.setModel(mm);
        DefaultComboBoxModel ym=new DefaultComboBoxModel(years);
        year_cm.setModel(ym);
        DefaultComboBoxModel h_m=new DefaultComboBoxModel(hours);
         DefaultComboBoxModel h_m_e=new DefaultComboBoxModel(hours);
        hour_start.setModel(h_m);
        hour_end.setModel(h_m_e);
        DefaultComboBoxModel min_m=new DefaultComboBoxModel(mins);
        DefaultComboBoxModel min_m_e=new DefaultComboBoxModel(mins);
        min_start.setModel(min_m);
        min_end.setModel(min_m_e);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rem_lb = new javax.swing.JLabel();
        loc_lb = new javax.swing.JLabel();
        Place = new javax.swing.JTextField();
        event_name_tx = new javax.swing.JTextField();
        year_cm = new javax.swing.JComboBox<>();
        Days_start_cm = new javax.swing.JComboBox<>();
        month_start_cm = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        date_lb = new javax.swing.JLabel();
        min_start = new javax.swing.JComboBox<>();
        hour_start = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        hour_end = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        min_end = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        Reminder_cm = new javax.swing.JComboBox<>();
        Add_button = new javax.swing.JButton();
        head_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Exit_btn = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        Time_label = new javax.swing.JLabel();
        constraint_label = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(580, 472));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(110, 89, 222));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(110, 89, 222));
        jLabel2.setText("/");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 20, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(110, 89, 222));
        jLabel3.setText("to");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, -1));

        rem_lb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rem_lb.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(rem_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 20, 30));

        loc_lb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loc_lb.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(loc_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 30, 20));

        Place.setForeground(new java.awt.Color(102, 102, 102));
        Place.setText("Location");
        Place.setBorder(null);
        Place.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PlaceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PlaceFocusLost(evt);
            }
        });
        Place.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlaceActionPerformed(evt);
            }
        });
        jPanel1.add(Place, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 270, 30));

        event_name_tx.setForeground(new java.awt.Color(102, 102, 102));
        event_name_tx.setText("Event Name");
        event_name_tx.setBorder(null);
        event_name_tx.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                event_name_txFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                event_name_txFocusLost(evt);
            }
        });
        event_name_tx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                event_name_txActionPerformed(evt);
            }
        });
        event_name_tx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                event_name_txKeyTyped(evt);
            }
        });
        jPanel1.add(event_name_tx, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 280, 30));

        year_cm.setForeground(new java.awt.Color(110, 89, 222));
        year_cm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                year_cmActionPerformed(evt);
            }
        });
        jPanel1.add(year_cm, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        Days_start_cm.setForeground(new java.awt.Color(110, 89, 222));
        Days_start_cm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Days_start_cmActionPerformed(evt);
            }
        });
        jPanel1.add(Days_start_cm, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        month_start_cm.setForeground(new java.awt.Color(110, 89, 222));
        month_start_cm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                month_start_cmActionPerformed(evt);
            }
        });
        jPanel1.add(month_start_cm, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(110, 89, 222));
        jLabel9.setText("/");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 10, -1));

        date_lb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        date_lb.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(date_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 20, 20));

        min_start.setForeground(new java.awt.Color(110, 89, 222));
        min_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                min_startActionPerformed(evt);
            }
        });
        jPanel1.add(min_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 40, -1));

        hour_start.setForeground(new java.awt.Color(110, 89, 222));
        hour_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hour_startActionPerformed(evt);
            }
        });
        jPanel1.add(hour_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 40, -1));

        jLabel11.setBackground(new java.awt.Color(110, 89, 222));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(110, 89, 222));
        jLabel11.setText(":");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 10, -1));

        hour_end.setForeground(new java.awt.Color(110, 89, 222));
        hour_end.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hour_endActionPerformed(evt);
            }
        });
        jPanel1.add(hour_end, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 40, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(110, 89, 222));
        jLabel12.setText(":");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 10, -1));

        min_end.setForeground(new java.awt.Color(110, 89, 222));
        min_end.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                min_endActionPerformed(evt);
            }
        });
        jPanel1.add(min_end, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 40, -1));

        jLabel13.setBackground(new java.awt.Color(110, 89, 222));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(110, 89, 222));
        jLabel13.setText(":");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 10, -1));

        Reminder_cm.setForeground(new java.awt.Color(110, 89, 222));
        Reminder_cm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0    minutes before", "5    minutes before", "15   minutes before", "30   minutes before", "1    hour before", "2    hour before" }));
        Reminder_cm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reminder_cmActionPerformed(evt);
            }
        });
        jPanel1.add(Reminder_cm, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        Add_button.setBackground(new java.awt.Color(110, 89, 222));
        Add_button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Add_button.setForeground(new java.awt.Color(255, 255, 255));
        Add_button.setText("ADD");
        Add_button.setBorder(null);
        Add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(Add_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 90, 30));

        head_panel.setBackground(new java.awt.Color(110, 89, 222));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Event");

        Exit_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Exit_btnMousePressed(evt);
            }
        });

        javax.swing.GroupLayout head_panelLayout = new javax.swing.GroupLayout(head_panel);
        head_panel.setLayout(head_panelLayout);
        head_panelLayout.setHorizontalGroup(
            head_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(head_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 317, Short.MAX_VALUE)
                .addComponent(Exit_btn)
                .addContainerGap())
        );
        head_panelLayout.setVerticalGroup(
            head_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, head_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(head_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Exit_btn))
                .addContainerGap())
        );

        jPanel1.add(head_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 40));

        jSeparator1.setForeground(new java.awt.Color(110, 89, 222));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 270, 10));

        jSeparator2.setForeground(new java.awt.Color(110, 89, 222));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 280, 10));
        jPanel1.add(Time_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 30, 20));

        constraint_label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        constraint_label.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(constraint_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 240, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Exit_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit_btnMousePressed
        // TODO add your handling code here:
        this.dispose();
                  event_name_tx.setText("");
                  Place.setText("");
                   Days_start_cm.setSelectedIndex(0);
                   month_start_cm.setSelectedIndex(0);
                   year_cm.setSelectedIndex(0);
                   hour_start.setSelectedIndex(0);
                    min_start.setSelectedIndex(0);
                    hour_end.setSelectedIndex(0);
                    min_end.setSelectedIndex(0);
                    Reminder_cm.setSelectedIndex(0);
                    constraint_label.setText("");
    }//GEN-LAST:event_Exit_btnMousePressed

    private void Add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_buttonActionPerformed

        
      //String FileNme="event_scd_cpp\\Event_scd\\Debug\\Event_scd.exe";
         String FileNme="event_scd_cpp\\map_ev_scd\\Event_scheduele_by_map\\Debug\\Event_scheduele_by_map.exe";
        char mode=Reminder_cm.getSelectedItem().toString().charAt(5);
        int rem = 0;
        if (mode=='m') {
            rem=Integer.parseInt(Reminder_cm.getSelectedItem().toString().substring(0, 2).replaceAll("\\s", ""));
        }
        else if(mode=='h')
        {
            rem=Integer.parseInt(Reminder_cm.getSelectedItem().toString().substring(0, 2).replaceAll("\\s", ""))*60;

        }
        System.out.println(current_user +"  "+cureent_password);
        String Args="/Add_Event"+" "+current_user+" "+cureent_password+" "+event_name_tx.getText()+" "+Place.getText()+" "+Days_start_cm.getSelectedItem().toString()+" "
        +month_start_cm.getSelectedItem().toString()+" "+year_cm.getSelectedItem().toString()+" "+hour_start.getSelectedItem().toString()+" "+min_start.getSelectedItem()+" "+
        Integer.toString(rem)+" "+hour_end.getSelectedItem().toString()+" "+min_end.getSelectedItem().toString();
        System.out.println(Args);
        boolean status=true;
        try {
            String run_cmd=RunCmd(FileNme, Args);
            System.out.println(Args);
            System.out.println("ADD_fn : "+run_cmd+"//");
            
            for (int i = 0; i < run_cmd.length(); i++) {
                System.out.println(i+" : "+run_cmd.charAt(i));
            }
            
            
            
            if (run_cmd.indexOf("1")!=-1) {
                constraint_label.setText("(This event is already exist)");
                status=false;
               
              }
               if (run_cmd.indexOf("2")!=-1) {
                constraint_label.setText("(You cannot add an event in the past)");
                   System.err.println("past.........");
                 status=false;
              }
              if (run_cmd.indexOf("3")!=-1) {
                constraint_label.setText("(This event intersects with another event)");
                status=false;
              }
                if (run_cmd.indexOf("4")!=-1) {
                constraint_label.setText("(Wrong time range)");
                status=false;
              }

              if (status) {
                  DefaultTableModel tm = (DefaultTableModel) table.getModel();
                  
                  g_code.table_full(current_user, cureent_password, table,"/Display",sp,empty_lb);
                  this.setVisible(false);
                   event_name_tx.setText("");
                  Place.setText("");
                   Days_start_cm.setSelectedIndex(0);
                   month_start_cm.setSelectedIndex(0);
                   year_cm.setSelectedIndex(0);
                   hour_start.setSelectedIndex(0);
                    min_start.setSelectedIndex(0);
                    hour_end.setSelectedIndex(0);
                    min_end.setSelectedIndex(0);
                    Reminder_cm.setSelectedIndex(0);
                    constraint_label.setText("");
            }
             
               
            
        } catch (IOException ex) {
            Logger.getLogger(ADD_set.class.getName()).log(Level.SEVERE, null, ex);
        }

        
    }//GEN-LAST:event_Add_buttonActionPerformed

    private void Reminder_cmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reminder_cmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Reminder_cmActionPerformed

    private void min_endActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_min_endActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_min_endActionPerformed

    private void hour_endActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hour_endActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hour_endActionPerformed

    private void hour_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hour_startActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hour_startActionPerformed

    private void min_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_min_startActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_min_startActionPerformed

    private void month_start_cmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_month_start_cmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_month_start_cmActionPerformed

    private void Days_start_cmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Days_start_cmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Days_start_cmActionPerformed

    private void year_cmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_year_cmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_year_cmActionPerformed

    private void event_name_txKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_event_name_txKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_event_name_txKeyTyped

    private void event_name_txActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_event_name_txActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_event_name_txActionPerformed

    private void event_name_txFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_event_name_txFocusLost
        // TODO add your handling code here:
        if (event_name_tx.getText().equals("")) {
            event_name_tx.setText("Event Name");
            event_name_tx.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_event_name_txFocusLost

    private void event_name_txFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_event_name_txFocusGained
        // TODO add your handling code here:
        if (event_name_tx.getText().equals("Event Name")) {
            event_name_tx.setText("");
            event_name_tx.setForeground(font_color);
        }

    }//GEN-LAST:event_event_name_txFocusGained

    private void PlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlaceActionPerformed

    private void PlaceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PlaceFocusLost
        // TODO add your handling code here:
        if (Place.getText().equals("")) {
            Place.setText("Location");
            Place.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_PlaceFocusLost

    private void PlaceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PlaceFocusGained
        // TODO add your handling code here:
        if (Place.getText().equals("Location")) {
            Place.setText("");
            Place.setForeground(font_color);
        }
    }//GEN-LAST:event_PlaceFocusGained
        public String RunCmd(String Filename,String Commands) throws IOException
    {
        Runtime rt =Runtime.getRuntime();
        Process proc;
        proc =rt.exec(Filename+" "+Commands);
        BufferedReader buf =new BufferedReader(
                new InputStreamReader(proc.getInputStream())
        
        );
        String Line,Result="";
        while((Line=buf.readLine())!=null)
        {
            Result+=Line+"\n";
        }
        return Result;
    }
             public void set_user(String user,String pass)
     {
         this.current_user=user;
         
         this.cureent_password=pass;
     }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADD_set.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADD_set.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADD_set.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADD_set.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADD_set().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Add_button;
    public javax.swing.JComboBox<String> Days_start_cm;
    private javax.swing.JLabel Exit_btn;
    public javax.swing.JTextField Place;
    public javax.swing.JComboBox<String> Reminder_cm;
    public javax.swing.JLabel Time_label;
    private javax.swing.JLabel constraint_label;
    public javax.swing.JLabel date_lb;
    public javax.swing.JTextField event_name_tx;
    public javax.swing.JPanel head_panel;
    public javax.swing.JComboBox<String> hour_end;
    public javax.swing.JComboBox<String> hour_start;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    public javax.swing.JLabel loc_lb;
    public javax.swing.JComboBox<String> min_end;
    public javax.swing.JComboBox<String> min_start;
    public javax.swing.JComboBox<String> month_start_cm;
    public javax.swing.JLabel rem_lb;
    public javax.swing.JComboBox<String> year_cm;
    // End of variables declaration//GEN-END:variables
}
