/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.scedule_gui;

import javax.swing.*;

/**
 *
 * @author user
 */
public class CREDITS_Pan extends javax.swing.JPanel {

    /**
     * Creates new form CREDITS_Pan
     */
    
    
    
    public CREDITS_Pan() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_label = new javax.swing.JLabel();
        dev1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dev4 = new javax.swing.JLabel();
        dev8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dev6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        dev7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        dev2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ending_statement = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        dev3 = new javax.swing.JLabel();
        main_sep = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        main_label.setBackground(new java.awt.Color(110, 89, 222));
        main_label.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        main_label.setForeground(new java.awt.Color(110, 89, 222));
        main_label.setText("Devloped By :");
        add(main_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 231, 50));

        dev1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dev1.setForeground(new java.awt.Color(110, 89, 222));
        dev1.setText("Youssef shehata");
        add(dev1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 140, 42));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 102, 255));
        jLabel3.setText("Dev :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 102, 255));
        jLabel4.setText("Dev :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, -1, -1));

        dev4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dev4.setForeground(new java.awt.Color(110, 89, 222));
        dev4.setText("Mohmed Ashraf");
        add(dev4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 140, 42));

        dev8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dev8.setForeground(new java.awt.Color(110, 89, 222));
        dev8.setText("Abdel-Rahmen Medhat");
        add(dev8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 190, 42));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 102, 255));
        jLabel9.setText("Dev :");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, -1));

        dev6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dev6.setForeground(new java.awt.Color(110, 89, 222));
        dev6.setText("Youssef Mohmed");
        add(dev6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 150, 42));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 102, 255));
        jLabel11.setText("Dev :");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        dev7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dev7.setForeground(new java.awt.Color(110, 89, 222));
        dev7.setText("Youssef Ryan");
        add(dev7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 115, 42));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 102, 255));
        jLabel13.setText("Dev :");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, -1, -1));

        dev2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dev2.setForeground(new java.awt.Color(110, 89, 222));
        dev2.setText("Samy Ahmed");
        add(dev2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 115, 42));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 102, 255));
        jLabel15.setText("Dev :");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, -1, -1));

        ending_statement.setBackground(new java.awt.Color(0, 0, 255));
        ending_statement.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        ending_statement.setForeground(new java.awt.Color(0, 0, 255));
        ending_statement.setText("Devolped by little of code and a lot of team work ");
        add(ending_statement, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 380, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 102, 255));
        jLabel17.setText("Dev :");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        dev3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dev3.setForeground(new java.awt.Color(110, 89, 222));
        dev3.setText("Saif Adel");
        add(dev3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 140, 42));

        main_sep.setBackground(new java.awt.Color(204, 153, 0));
        main_sep.setForeground(new java.awt.Color(255, 153, 102));
        main_sep.setOrientation(javax.swing.SwingConstants.VERTICAL);
        main_sep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 20));
        add(main_sep, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 20, 70));

        jSeparator3.setForeground(new java.awt.Color(204, 0, 204));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 700, 10));

        jSeparator8.setForeground(new java.awt.Color(204, 0, 204));
        add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 580, 10));

        jSeparator10.setForeground(new java.awt.Color(204, 0, 204));
        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 10, 300));

        jSeparator11.setForeground(new java.awt.Color(204, 0, 204));
        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, 10, 300));

        jSeparator12.setForeground(new java.awt.Color(204, 0, 204));
        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 10, 280));

        jSeparator13.setForeground(new java.awt.Color(153, 102, 255));
        jSeparator13.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 10, 280));

        jSeparator14.setForeground(new java.awt.Color(204, 0, 204));
        add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 580, 10));

        jSeparator9.setForeground(new java.awt.Color(204, 0, 204));
        add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 430, 10));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel dev1;
    public javax.swing.JLabel dev2;
    public javax.swing.JLabel dev3;
    public javax.swing.JLabel dev4;
    public javax.swing.JLabel dev6;
    public javax.swing.JLabel dev7;
    public javax.swing.JLabel dev8;
    public javax.swing.JLabel ending_statement;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JSeparator jSeparator10;
    public javax.swing.JSeparator jSeparator11;
    public javax.swing.JSeparator jSeparator12;
    public javax.swing.JSeparator jSeparator13;
    public javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator3;
    public javax.swing.JSeparator jSeparator8;
    public javax.swing.JSeparator jSeparator9;
    public javax.swing.JLabel main_label;
    public javax.swing.JSeparator main_sep;
    // End of variables declaration//GEN-END:variables
}

