/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.scedule_gui;
import java.awt.Color;
import java.util.AbstractCollection.*;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Login_gui_form extends javax.swing.JFrame {
  Generics g_code=new Generics();
  Events event_screen=new Events();
  ImageIcon hi_icon1=new ImageIcon("Login_form_images\\hi1.gif");
  ImageIcon hi_icon2=new ImageIcon("Login_form_images\\hi2.gif");
  ImageIcon hi_icon3=new ImageIcon("Login_form_images\\hi3.gif");
  ImageIcon hi_icon4=new ImageIcon("Login_form_images\\hi4.gif");
  ImageIcon hi_icon5=new ImageIcon("Login_form_images\\hi5.gif");
  ImageIcon hi_icon6=new ImageIcon("Login_form_images\\hi6.gif");
  ImageIcon hi_icon7=new ImageIcon("Login_form_images\\hi7.gif");
  ImageIcon hi_icon8=new ImageIcon("Login_form_images\\hi8.gif");
   ImageIcon hi_icon9=new ImageIcon("Login_form_images\\hi9.gif");
    ImageIcon hi_icon10=new ImageIcon("Login_form_images\\hi10.gif");
  ImageIcon[]imageIcons_arr={hi_icon1,hi_icon2,hi_icon3,hi_icon4,hi_icon5,hi_icon6,hi_icon7,hi_icon8,hi_icon9,hi_icon10};
  Random rand=new Random();
 
  int image_index=rand.nextInt(10);
   boolean hide_flag=true;
  ImageIcon user_icon=new ImageIcon("Images\\icons8_user_20px.png");
  ImageIcon pass_icon=new ImageIcon("Images\\icons8_password_20px.png");
  ImageIcon visible_btn=new ImageIcon("Images\\show.png");
   ImageIcon invisible_btn=new ImageIcon("Images\\invisible.png");
   //ImageIcon icon1=new ImageIcon("Loading_images\\Events-pana.png");
    public Login_gui_form() {
        initComponents();

             Toolkit toolkit=getToolkit();
    Dimension size=toolkit.getScreenSize();
   
    this.setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
       //Scale_image(hi_icon, Image_hi_label);
        this.Image_hi_label.setIcon(imageIcons_arr[image_index]);
        this.user_icon_label1.setIcon(user_icon);
        this.pass_icon_label.setIcon(pass_icon);
        Scale_image(visible_btn, visible_password);
        sign_in.setEnabled(false);
        Sign_up.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back_ground = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Image_hi_label = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        user_field = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        visible_password = new javax.swing.JLabel();
        pass_icon_label = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        sign_in = new javax.swing.JButton();
        Sign_up = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        user_icon_label1 = new javax.swing.JLabel();
        pass_field = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();
        invalid_pass_user = new javax.swing.JLabel();
        user_space = new javax.swing.JLabel();
        pass_space1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Event Scheduele");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Back_ground.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(Image_hi_label, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Image_hi_label, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user_field.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        user_field.setBorder(null);
        user_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                user_fieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                user_fieldFocusLost(evt);
            }
        });
        jPanel5.add(user_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 360, 30));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel5.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 400, 10));

        visible_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                visible_passwordMousePressed(evt);
            }
        });
        jPanel5.add(visible_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 30, 20));
        jPanel5.add(pass_icon_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 40, 30));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel5.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 400, 10));

        sign_in.setBackground(new java.awt.Color(153, 0, 153));
        sign_in.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sign_in.setForeground(new java.awt.Color(255, 255, 255));
        sign_in.setText("Sign In");
        sign_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sign_inActionPerformed(evt);
            }
        });
        jPanel5.add(sign_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 130, 40));

        Sign_up.setBackground(new java.awt.Color(153, 0, 153));
        Sign_up.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Sign_up.setForeground(new java.awt.Color(255, 255, 255));
        Sign_up.setText("Sign up");
        Sign_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sign_upActionPerformed(evt);
            }
        });
        jPanel5.add(Sign_up, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 130, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("agree with terms and policies");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 240, 30));
        jPanel5.add(user_icon_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 40, 30));

        pass_field.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pass_field.setBorder(null);
        pass_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pass_fieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pass_fieldFocusLost(evt);
            }
        });
        pass_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_fieldActionPerformed(evt);
            }
        });
        jPanel5.add(pass_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 320, 30));

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox1StateChanged(evt);
            }
        });
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel5.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, 30));

        invalid_pass_user.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        invalid_pass_user.setForeground(new java.awt.Color(204, 0, 0));
        jPanel5.add(invalid_pass_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 330, 20));

        user_space.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        user_space.setForeground(new java.awt.Color(204, 0, 0));
        jPanel5.add(user_space, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 330, 20));

        pass_space1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pass_space1.setForeground(new java.awt.Color(204, 0, 0));
        jPanel5.add(pass_space1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 330, 20));

        jPanel1.setBackground(new java.awt.Color(110, 89, 222));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Events Scheduler");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 11, 308, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 590, 15));

        jLabel2.setFont(new java.awt.Font("Sitka Text", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("All Your Dates In One Place");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 180, -1));

        javax.swing.GroupLayout Back_groundLayout = new javax.swing.GroupLayout(Back_ground);
        Back_ground.setLayout(Back_groundLayout);
        Back_groundLayout.setHorizontalGroup(
            Back_groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Back_groundLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Back_groundLayout.setVerticalGroup(
            Back_groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Back_groundLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Back_groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(Back_ground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Sign_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sign_upActionPerformed
              invalid_pass_user.setText("");
              pass_space1.setText("");
              user_space.setText("");
              boolean status=true;
              if (user_field.getText().isEmpty()) {
                user_space.setText("You must Enter user name !");
              // JOptionPane.showMessageDialog(this,"You must Enter user name and password !","Alert",JOptionPane.WARNING_MESSAGE);
                user_field.setText("");
               status=false;

                
            }
               if (pass_field.getText().isEmpty()) {
                pass_space1.setText("You must Enter Password !");
                //JOptionPane.showMessageDialog(this,"You must Enter user name and password !","Alert",JOptionPane.WARNING_MESSAGE);
                
                pass_field.setText("");
                status=false;

                
            }
             if(user_field.getText().contains(" "))
            {
                user_space.setText("Use name can't contains spaces !");
               // JOptionPane.showMessageDialog(this,"Use name and password can't contains spaces !","Alert",JOptionPane.WARNING_MESSAGE);
                user_field.setText("");
                status=false;
                

            }
               if(pass_field.getText().contains(" "))
            {
                pass_space1.setText("Password can't contains spaces !");
               // JOptionPane.showMessageDialog(this,"Use name and password can't contains spaces !","Alert",JOptionPane.WARNING_MESSAGE);
                pass_field.setText("");
                status=false;
                

            }
            if(status)
            {
                  try {
//                 String FileNme="event_scd_cpp\\Event_scd\\Debug\\Event_scd.exe";
                  String FileNme="event_scd_cpp\\map_ev_scd\\Event_scheduele_by_map\\Debug\\Event_scheduele_by_map.exe";
                 String Args="/Sign_up"+" "+user_field.getText()+" "+pass_field.getText();
                 String Args2="/Display"+" "+user_field.getText()+" "+pass_field.getText();
                String res=g_code.RunCmd(FileNme, Args);
                if (res.indexOf('1')!=-1) {
                 this.setVisible(false);
                  
                  String events=g_code.RunCmd(FileNme, Args2);
                 event_screen.set_user(user_field.getText(),pass_field.getText(),events);
                 
                
                 event_screen.setVisible(true);
                 
                  
            }
            else if (res.indexOf('0')!=-1) {
                invalid_pass_user.setText("This user name is already exist");
                //JOptionPane.showMessageDialog(this,"This user name is already exist","Alert",JOptionPane.WARNING_MESSAGE);
                user_field.setText("");
                pass_field.setText("");
            }
            else{System.out.println("wrong....");}
                
            } catch (IOException ex) {
               
            }
            }
    }//GEN-LAST:event_Sign_upActionPerformed

    private void visible_passwordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visible_passwordMousePressed
        if (hide_flag) {
            this.pass_field.setEchoChar((char)0);
            Scale_image(invisible_btn, visible_password);
            hide_flag=false;
        }
        else if(!hide_flag)
        {
            this.pass_field.setEchoChar('\u25cf');
            Scale_image(visible_btn, visible_password);
            hide_flag=true;
        }
    }//GEN-LAST:event_visible_passwordMousePressed

    private void pass_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_fieldActionPerformed

    private void sign_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sign_inActionPerformed
              invalid_pass_user.setText("");
              pass_space1.setText("");
              user_space.setText("");
            boolean status=true;
            if (user_field.getText().isEmpty()) {
                user_space.setText("You must Enter user name !");
               //JOptionPane.showMessageDialog(this,"You must Enter user name and password !","Alert",JOptionPane.WARNING_MESSAGE);
                user_field.setText("");
                status=false;
                

                
            }
               if (pass_field.getText().isEmpty()) {
                pass_space1.setText("You must Enter password !");
               //JOptionPane.showMessageDialog(this,"You must Enter user name and password !","Alert",JOptionPane.WARNING_MESSAGE);
                pass_field.setText("");
                status=false;

                
            }
             if(status)
               {
                  try {
                // String FileNme="event_scd_cpp\\Event_scd\\Debug\\Event_scd.exe";
                   String FileNme="event_scd_cpp\\map_ev_scd\\Event_scheduele_by_map\\Debug\\Event_scheduele_by_map.exe";
                 String Args="/Sign_in"+" "+user_field.getText()+" "+pass_field.getText();
                 String Args2="/Display"+" "+user_field.getText()+" "+pass_field.getText();
                String res=g_code.RunCmd(FileNme, Args);
                if (res.indexOf("1")!=-1) {
                 this.setVisible(false);
                  String events=g_code.RunCmd(FileNme, Args2);
                    event_screen.set_user(user_field.getText(),pass_field.getText(),events);
                    System.out.println(event_screen.cu_user_name);
                    System.err.println("data : "+event_screen.upcoming_area_class.t_data);
                    //System.out.println(event_screen.cu_user_name);
                   //System.out.println(event_screen.cu_user_pass);
                   
                   
                   
                   // System.out.println(event_screen.upcoming_area_class.t_data);
                  event_screen.setVisible(true);
                 
                  
            }
            else if (res.indexOf("0")!=-1) {
                invalid_pass_user.setText("Invalid user name or password !");
                //JOptionPane.showMessageDialog(this,"Invalid user name or password !","Alert",JOptionPane.WARNING_MESSAGE);
                user_field.setText("");
                pass_field.setText("");
            }
            else{System.out.println("wrong....");System.out.println(res);}
                
            } catch (IOException ex) {
                
            }
               }        
    }//GEN-LAST:event_sign_inActionPerformed

    private void jCheckBox1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox1StateChanged
        // TODO add your handling code here:
        if (jCheckBox1.isSelected()) {
        sign_in.setEnabled(true);
        Sign_up.setEnabled(true);
        }
        else
        {
        sign_in.setEnabled(false);
        Sign_up.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBox1StateChanged

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void user_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_user_fieldFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_user_fieldFocusGained

    private void user_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_user_fieldFocusLost
        // TODO add your handling code here:

       
    }//GEN-LAST:event_user_fieldFocusLost

    private void pass_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass_fieldFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_pass_fieldFocusGained

    private void pass_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass_fieldFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_pass_fieldFocusLost

    /**
     * @param args the command line arguments
     */
            public void Scale_image(ImageIcon icon,JLabel label)
    {
        Image img=icon.getImage();
        Image immgScaled=img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledicon=new ImageIcon(immgScaled);
        label.setIcon(scaledicon);
    }
            
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_gui_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_gui_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_gui_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_gui_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Back_ground;
    private javax.swing.JLabel Image_hi_label;
    private javax.swing.JButton Sign_up;
    private javax.swing.JLabel invalid_pass_user;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JPasswordField pass_field;
    private javax.swing.JLabel pass_icon_label;
    private javax.swing.JLabel pass_space1;
    private javax.swing.JButton sign_in;
    private javax.swing.JTextField user_field;
    private javax.swing.JLabel user_icon_label1;
    private javax.swing.JLabel user_space;
    private javax.swing.JLabel visible_password;
    // End of variables declaration//GEN-END:variables
}
