/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.scedule_gui;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author user
 */
public class Settings_panel extends javax.swing.JPanel {

    /**
     * Creates new form Settings_panel
     */
    Generics g_code=new Generics();
    ImageIcon lav_icon=new ImageIcon("Modes\\Lavandr.jpg");
    ImageIcon red_icon=new ImageIcon("Modes\\Bloddy_red.jpg");
    ImageIcon blue_icon=new ImageIcon("Modes\\Sky.jpg");
    ImageIcon dark_icon=new ImageIcon("Modes\\Dark.jpg");
    ImageIcon log_icon=new ImageIcon("Images\\logout.png");
    Events e;
    public Settings_panel() {
        initComponents();
       Scale_image(lav_icon, lavendr_btn);
         Scale_image(red_icon, red_btn);
        Scale_image(blue_icon, blue_btn);
        Scale_image(dark_icon, dark_btn);
        Log_out.setIcon(log_icon);
//          lavendr_btn.setIcon(lav_icon);
//          red_btn.setIcon(red_icon);
//          blue_btn.setIcon(blue_icon);
//          dark_btn.setIcon(dark_icon);
        
    }
            public void Scale_image(ImageIcon icon,JLabel label)
    {
        Image img=icon.getImage();
        Image immgScaled=img.getScaledInstance(155, 130, Image.SCALE_SMOOTH);
        ImageIcon scaledicon=new ImageIcon(immgScaled);
        label.setIcon(scaledicon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        theme_sep = new javax.swing.JSeparator();
        themes_lb = new javax.swing.JLabel();
        main_panel = new javax.swing.JPanel();
        lavendr_btn = new javax.swing.JLabel();
        red_btn = new javax.swing.JLabel();
        dark_btn = new javax.swing.JLabel();
        blue_btn = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        Log_out = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jLabel5.setBackground(new java.awt.Color(110, 89, 222));
        jLabel5.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setText("Chilly Mode");

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        theme_sep.setBackground(new java.awt.Color(0, 0, 255));
        theme_sep.setForeground(new java.awt.Color(0, 0, 255));
        theme_sep.setOrientation(javax.swing.SwingConstants.VERTICAL);
        theme_sep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 20));
        add(theme_sep, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 11, 16, 66));

        themes_lb.setBackground(new java.awt.Color(110, 89, 222));
        themes_lb.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        themes_lb.setForeground(new java.awt.Color(110, 89, 222));
        themes_lb.setText("Themes");
        add(themes_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 28, 231, 39));

        main_panel.setBackground(new java.awt.Color(255, 255, 255));
        main_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lavendr_btn.setBackground(new java.awt.Color(51, 0, 255));
        lavendr_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        main_panel.add(lavendr_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 151, 130));

        red_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        main_panel.add(red_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 140, 130));

        dark_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        main_panel.add(dark_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 150, 130));

        blue_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        main_panel.add(blue_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 140, 130));

        add(main_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 610, 130));

        jLabel3.setBackground(new java.awt.Color(110, 89, 222));
        jLabel3.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("Chilly Mode");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 255));
        jLabel4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(110, 89, 222));
        jLabel4.setText("Clear sky Mode");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, -1, -1));

        jLabel6.setBackground(new java.awt.Color(153, 153, 153));
        jLabel6.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Dark Mode");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, -1, -1));

        jLabel8.setBackground(new java.awt.Color(153, 51, 255));
        jLabel8.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(110, 89, 222));
        jLabel8.setText("Lavandr Mode");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 255));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 650, 10));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 255));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 650, 10));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 255));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 10, 150));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 255));
        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, 10, 150));

        Log_out.setBackground(new java.awt.Color(0, 0, 204));
        Log_out.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Log_out.setForeground(new java.awt.Color(255, 255, 255));
        Log_out.setText("Log out");
        Log_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Log_outActionPerformed(evt);
            }
        });
        add(Log_out, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 230, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void Log_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Log_outActionPerformed
        // TODO add your handling code here:
        e.dispose();
        Login_gui_form l=new Login_gui_form();
        l.setVisible(true);
        //l.event_screen.setTime();
       
        
        System.out.println("Logout");
        
    }//GEN-LAST:event_Log_outActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Log_out;
    public javax.swing.JLabel blue_btn;
    public javax.swing.JLabel dark_btn;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JSeparator jSeparator5;
    public javax.swing.JSeparator jSeparator6;
    public javax.swing.JSeparator jSeparator7;
    public javax.swing.JSeparator jSeparator8;
    public javax.swing.JLabel lavendr_btn;
    public javax.swing.JPanel main_panel;
    public javax.swing.JLabel red_btn;
    public javax.swing.JSeparator theme_sep;
    public javax.swing.JLabel themes_lb;
    // End of variables declaration//GEN-END:variables
}
